### ISSUE TITLE
你好，  python manage.py  makemigrations 有个报错

### ISSUE THREAD

**Issue by ljb-2000** [roddyofchina/SimpletourDevops#1]
**[root@centos-master** SimpletourDevops]# python manage.py  makemigrations
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/usr/lib64/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib64/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib64/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named domainmanager

**Comment by roddyofchina** [comment]
你需要把domainmanager去掉，同时把base.html中关于domainmanger的html代码屏蔽掉，这个功能正在开发中！！sorry

**Comment by ljb-2000** [comment]
好的，感谢及时回复！

**Comment by ljb-2000** [comment]
请问下您用的是那一个admin后台模板

**Comment by roddyofchina** [comment]
UBOLD

**Comment by ljb-2000** [comment]
好的 感谢！最新有什么开发计划吗

**Comment by roddyofchina** [comment]
后面打算把docker容器的功能完善了，建立容器，状态，监控等

**Comment by ljb-2000** [comment]
好，期待 UBOLD有免费下载的版本 网上搜了下都是付费的

**Comment by roddyofchina** [comment]
加我QQ：923401910  我传一个给你

**Comment by ljb-2000** [comment]
已加
