### ISSUE TITLE
你好,启动时报错ImportError: No module named apps

### ISSUE THREAD

**Issue by lylsq** [roddyofchina/SimpletourDevops#2]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/SimpletourDevops/SimpletourDevops/apps.py", line 6, in <module>
    from suit.apps import DjangoSuitConfig
ImportError: No module named apps

**Comment by roddyofchina** [comment]
有装Suit模块吗,没有的话请安装一下   https://github.com/darklow/django-suit/tarball/v2-vertical

**Comment by lylsq** [comment]
![image](https://cloud.githubusercontent.com/assets/11774673/23009616/f717872c-f451-11e6-982d-c04c6386652a.png)
您好,我已经安装django-suit,但是还是显示该错误
![image](https://cloud.githubusercontent.com/assets/11774673/23009631/1663d23e-f452-11e6-9178-c40b2cb5b7e1.png)

**Comment by roddyofchina** [comment]
目前使用的django-suit是v2版本，需要使用 pip install  https://github.com/darklow/django-suit/tarball/v2进行安装。

**Comment by lylsq** [comment]
非常感谢,已经成功安装

**Comment by roddyofchina** [comment]
好的，这边代码我已经全部更新，相关安装报错问题已经修复

**Comment by lylsq** [comment]
你好,环境搭建好了,注册了账户,点击登录没有反应,请教如何解决

**Comment by roddyofchina** [comment]
加我QQ吧：923401910 我帮你看下
